[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
extra_scripts = pre:pre_extra_script.py
lib_deps =
    knolleary/PubSubClient
    adafruit/Adafruit AMG88xx Library
    tanakamasayuki/TensorFlowLite_ESP32
